version '3.8'

services:
  db:
    container_name:parkin_db
    image:docker
    restart:always
    ports
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      -db_data_autospace:/var/lib/postgresql/data

volumes:
  db_data_parkin: